### PR TITLE
#168312603: Fix search to include a global search

### PR DESCRIPTION
**Pull request by JamesMudidi**
## Description ##
Include a global search field that takes in more keywords for search options reducing the number of independent searches options tp improve the user search experience.

## Type of change ##
Please select the relevant option
- [x] Bug fix(a non-breaking change which fixes an issue)
- [ ] New feature(a non-breaking change which adds functionality)
- [ ] Breaking change(fix of feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ##
Please describe the tests that you ran to verify your changes
- [ ] End to end test
- [ ] Integration test
- [ ] unit test

## How to test the functionality? ##
- Setup the repo locally.
- Checkout to `bg-fix-search-168312603`.
- Run the python server `python manage.py runserver`
- Open postman and run a `Get` request on `http://localhost:8000/api/v1/properties/?` using the `search` parameter

## Checklist: ##
- [x] My code follows the style guidelines of this project
- [x] I have linted my code prior to submission
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing tests pass locally with my changes

## Related Pivotal Tracker stories ##
[ #168312603](https://www.pivotaltracker.com/story/show/168312603)

### CODE REVIEW

**Review by alexxsanya — COMMENTED** [review]
@JamesMudidi well done on this. Everything works as expected. Otherwise, rename this PR name with the appropriate format.

**Review by Manorlds-Eaglespark — APPROVED** [review]
Tested and works as should. Good work.

**Review by alexxsanya — APPROVED** [review]
LTGM now @JamesMudidi. Well done on this.

**Review by CryceTruly — APPROVED** [review]
Looks good.

**Review by dorothyas — APPROVED** [review]

**Review by wangonya — APPROVED** [review]
Works as expected.

**Review by Tevinthuku — APPROVED** [review]
Good stuff @JamesMudidi , works as expected

**Review by neelxie — APPROVED** [review]

**Review by Victoradukwu — APPROVED** [review]
Nice work

**Review by Rhytah — APPROVED** [review]

**Review by Niyitangasam — APPROVED** [review]
Great work

**Pull request merged**
